# Try Catch

try:
except (ExceptionName1, ExceptionName2) as error:
except ExceptionName3 as error:
else: #this will only execute there was no exception
finally: #this will always execute
